### ISSUE TITLE
SNS 간편 로그인 / 회원가입 기능 구현 

### ISSUE THREAD

**Issue by Dokuny** [ChocoTeamTeam/ToGather-BE#1]
## Description ✏
- OAuth2 + JWT 를 이용한 로그인 기능 구현 입니다.
- 지원하고자 하는 Provider는 아래와 같습니다.
  - 카카오
  - 네이버
  - 구글
  - 깃허브
- 로그인 성공 시, JWT 토큰을 발급합니다.

## Todo 📝
- [x] Spring Security 및 OAuth 초기 세팅
- [x] Provider 별 로그인 구현
- [x] JWT 토큰 발급
- [x] Spring Security에 JWT 적용
- [x] 로그인 API 문서화
- [x] 테스트 작성

## ETC 📌
- 기타 문의 사항이 있다면 글 남겨주시거나 연락주시기 바랍니다.
