### ISSUE TITLE
프로젝트 상태 변경 배치작업

### ISSUE THREAD

**Issue by devjy39** [ChocoTeamTeam/ToGather-BE#58]
## Description ✏
- 마감일이 지난 프로젝트의 상태 COMPLETE으로 변경 작업

## Todo 📝
- [x] 배치 환경 구성
- [x] 배치 JOB 구현
- [x] 배치 JOB TEST 코드 작성
